apiVersion: v2
appVersion: 1.6.8
description: Restorecommerce facade-srv
home: https://docs.restorecommerce.io/facade-srv/index.html
icon: https://avatars0.githubusercontent.com/u/8339525
maintainers:
- email: info@restorecommerce.io
  name: restorecommerce
  url: https://restorecommerce.io/
name: facade-srv
sources:
- https://github.com/restorecommerce/facade-srv
type: application
version: 0.1.44
